[package]
name = "jeod_interactions"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { workspace = true }
jeod_atmosphere = { path = "../jeod_atmosphere" }
jeod_quantities = { path = "../jeod_quantities" }
uom = { workspace = true }

[dev-dependencies]
jeod_dynamics = { path = "../jeod_dynamics" }
jeod_ephemeris = { path = "../jeod_ephemeris" }
jeod_gravity = { path = "../jeod_gravity" }
jeod_math = { path = "../jeod_math" }
jeod_planet = { path = "../jeod_planet" }
jeod_test_data = { path = "../jeod_test_data" }
jeod_time = { path = "../jeod_time" }
