[package]
name = "jeod_frames"
version = "0.1.0"
edition = "2021"

[dependencies]
jeod_math = { path = "../jeod_math" }
glam = { workspace = true }

[dev-dependencies]
jeod_math = { path = "../jeod_math", features = ["test-utils"] }
jeod_test_data = { path = "../jeod_test_data" }
jeod_time = { path = "../jeod_time" }
