[package]
name = "jeod_gravity"
version = "0.1.0"
edition = "2021"

[dependencies]
jeod_math = { path = "../jeod_math" }
jeod_dynamics = { path = "../jeod_dynamics" }
glam = { workspace = true }
log = "0.4"
thiserror = { workspace = true }

[dev-dependencies]
jeod_test_data = { path = "../jeod_test_data" }
jeod_time = { path = "../jeod_time" }
jeod_frames = { path = "../jeod_frames" }
