[package]
name = "jeod_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
jeod_math = { path = "../jeod_math" }
jeod_dynamics = { path = "../jeod_dynamics" }
jeod_gravity = { path = "../jeod_gravity" }
jeod_time = { path = "../jeod_time" }
jeod_frames = { path = "../jeod_frames" }
jeod_atmosphere = { path = "../jeod_atmosphere" }
jeod_interactions = { path = "../jeod_interactions" }
glam = { workspace = true }
log = { workspace = true }
