[package]
name = "bevy_jeod_interactions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
glam = { workspace = true }
jeod_dynamics = { path = "../jeod_dynamics" }
jeod_interactions = { path = "../jeod_interactions" }
jeod_sim = { path = "../jeod_sim" }
jeod_atmosphere = { path = "../jeod_atmosphere" }
bevy_jeod_dynamics = { path = "../bevy_jeod_dynamics" }
