//! Tier 2: validate the MET atmosphere model against JEOD's `SIM_MET`
//! reference outputs.
//!
//! JEOD ships a Trick verification sim at
//! `models/environment/atmosphere/MET/verif/SIM_MET/` which sweeps the MET
//! model across altitude (`RUN_T01_MET_VER`, `RUN_T02_MET_VER`) and longitude
//! (`RUN_T03_GRAM_MET`) at fixed solar-activity conditions. The CSV outputs
//! live in `test_data/met_t0{1,2,3}_*.csv` and are regenerated by the
//! Docker `xtask regenerate-tier3` workflow.
//!
//! Each row encodes:
//!   sample_index, density (kg/m^3), temperature (K),
//!   altitude (m), latitude (rad), longitude (rad)
//!
//! All rows share the same epoch (`time_utc` is frozen at t=0) and the same
//! solar-activity inputs (`f10=f10b=230`, `geo_index=20.30`, type=Ap). RUNs
//! T01 and T02 hold lat/lon constant and sweep altitude; RUN T03 sweeps
//! longitude (and toggles altitude between 650.0 km and 649.9999 km).
//!
//! Note: in RUN T01 and RUN T02 the first sample is a duplicate from Trick's
//! initialization step (sample 0 == sample 1). That is a quirk of the JEOD
//! sim's `add_read` time-tagged reset pattern, not of our model. We detect
//! this dynamically (rather than hard-coding a skip) so RUN T03 — whose row
//! 0 differs from row 1 — is fully exercised.

use astrodyn_atmosphere::met::{GeoIndexType, MetAtmosphere};
use astrodyn_verif_jeod::{atmosphere_verif::load_met_run_csv, tier3_csv::test_data_path};

/// Common solar-activity configuration used by every `SIM_MET` RUN.
/// Matches `models/environment/atmosphere/MET/verif/SIM_MET/SET_test/input_core.py`.
fn sim_met_atmos() -> MetAtmosphere {
    MetAtmosphere {
        f10: 230.0,
        f10b: 230.0,
        geo_index: 20.30,
        geo_index_type: GeoIndexType::Ap,
    }
}

/// TJT (Truncated Julian Time = MJD - 40000) for `RUN_T03_GRAM_MET` and any
/// other RUN that does not override `astrodyn_time.time_utc.set_date_and_time`.
///
/// `SET_test/input_core.py` sets UTC to `(2000, 1, 1, 1, 31, 48.0)` then
/// turns the `astrodyn_time` sim object off at t=0, so every `update_atmosphere`
/// call sees this same TJT.
///
/// MJD(2000-01-01 00:00 UTC) = 51544.0; adding 1h31m48s = 5508s = 0.06375 d
/// gives MJD = 51544.06375 and TJT = MJD - 40000 = 11544.06375.
const SIM_MET_DEFAULT_TJT: f64 = 11544.0 + 5508.0 / 86400.0;

/// TJT for `RUN_T01_MET_VER`. `input.py` overrides UTC to
/// `(1995, 1, 1, 0, 0, 1.0)`. MJD(1995-01-01 00:00 UTC) = 49718; adding
/// the 1-second offset gives MJD = 49718 + 1/86400 and TJT = 9718 + 1/86400.
const SIM_MET_T01_TJT: f64 = 9718.0 + 1.0 / 86400.0;

fn run_csv_test(label: &str, csv_name: &str, tjt: f64, density_tol: f64, temperature_tol: f64) {
    let csv_path = test_data_path(csv_name);
    let rows = load_met_run_csv(&csv_path);
    assert!(
        rows.len() >= 3,
        "{}: expected at least three rows, got {}",
        label,
        rows.len()
    );

    let atmos = sim_met_atmos();

    let mut max_density_relerr = 0.0_f64;
    let mut max_temp_abserr = 0.0_f64;

    // Drop Trick's initialization artifact only when present: in RUN T01 and
    // RUN T02 the sim's `add_read` replays the initial input at t=0, so row 0
    // duplicates row 1 (same altitude/lat/lon and identical density/temp). In
    // RUN T03 the first read is a real sample distinct from row 1, so we keep
    // it. Detect by exact equality of the geodetic position fields.
    let r0 = &rows[0];
    let r1 = &rows[1];
    let skip_first = r0.altitude_m == r1.altitude_m
        && r0.latitude_rad == r1.latitude_rad
        && r0.longitude_rad == r1.longitude_rad;
    let start = if skip_first { 1 } else { 0 };
    for row in rows.iter().skip(start) {
        let alt_km = row.altitude_m / 1000.0;
        let state = atmos.density(alt_km, row.latitude_rad, row.longitude_rad, tjt);

        let drelerr = (state.density - row.density).abs() / row.density;
        let terr = (state.temperature - row.temperature).abs();
        max_density_relerr = max_density_relerr.max(drelerr);
        max_temp_abserr = max_temp_abserr.max(terr);
    }

    eprintln!(
        "{label}: max density rel err = {max_density_relerr:.3e}, max temperature abs err = {max_temp_abserr:.3e} K"
    );

    assert!(
        max_density_relerr < density_tol,
        "{label}: max density relative error {max_density_relerr:.3e} exceeds tolerance {density_tol:.3e}"
    );
    assert!(
        max_temp_abserr < temperature_tol,
        "{label}: max temperature error {max_temp_abserr:.3e} K exceeds tolerance {temperature_tol:.3e} K"
    );
}

/// `RUN_T01_MET_VER`: 11 altitude samples between 120 km and 140 km at
/// (lat, lon) = (28.45°, -80.53°). Stresses the polynomial molecular-weight
/// branch (alt < 105 km is excluded; samples sit just above the barometric
/// ceiling so the diffusion-equation branch dominates).
#[test]
fn tier2_atmosphere_met_run_t01_low_altitude_sweep() {
    // Tier 2 against bit-exact JEOD reference: observed errors sit at the
    // f64 noise floor (rel-density ≈ 3e-16, temperature ≈ 6e-14 K). The 1e-12
    // floor is intentionally fixed — not the Tier 3 "max × 1.05" policy from
    // CLAUDE.md, which only governs trajectory cross-validation reports
    // (`CrossvalReport`). Tier 2 vector-match tests assert bit-equality up to
    // arithmetic ordering, so the threshold lives slightly above the highest
    // plausible noise (~ULP × dominant magnitude) and well below any physical
    // significance. Loosening this would silently mask a real algorithmic
    // divergence from the JEOD MET kernel.
    run_csv_test(
        "tier2_atmosphere_met_run_t01_low_altitude_sweep",
        "met_t01_met.csv",
        SIM_MET_T01_TJT,
        1.0e-12, // density relative
        1.0e-12, // temperature K
    );
}

/// `RUN_T02_MET_VER`: 19 altitude samples spanning 100 km to 1000 km at
/// (lat, lon) = (55°, 45°). Exercises every branch — barometric (≤105 km),
/// diffusion (105–500 km), helium fairing (440–500 km), and hydrogen above
/// 500 km.
#[test]
fn tier2_atmosphere_met_run_t02_full_altitude_sweep() {
    run_csv_test(
        "tier2_atmosphere_met_run_t02_full_altitude_sweep",
        "met_t02_met.csv",
        SIM_MET_DEFAULT_TJT,
        1.0e-12,
        1.0e-12,
    );
}

/// `RUN_T03_GRAM_MET`: 37 longitude samples at altitudes alternating between
/// 650.0 km and 649.9999 km, lat=28.45°. Stresses the longitude/solar-hour
/// dependency above the helium-fairing height.
#[test]
fn tier2_atmosphere_met_run_t03_longitude_sweep() {
    run_csv_test(
        "tier2_atmosphere_met_run_t03_longitude_sweep",
        "met_t03_gram_met.csv",
        SIM_MET_DEFAULT_TJT,
        1.0e-12,
        1.0e-12,
    );
}
