//! Tier 2: SIM_RNP_J2000_prop — Earth RNP transform cross-validation.
//!
//! This is a **Tier 2** cross-validation, not Tier 3: it does not run through
//! `Simulation::step()`. The RNP transform is a pure function of time, so this
//! reads JEOD's reference CSV and calls the production `astrodyn_frames`
//! functions (`precession_matrix`, `nutation`, `gast_rotation_matrix`)
//! directly, comparing the matrices element-wise. There is no integrator or
//! ECS path here, hence no Bevy-parity counterpart (and no `tier3_` prefix /
//! parity-coverage topic). RNP *as used in propagation* (`EarthRNP` driving
//! the planet-fixed frame for non-spherical gravity) is exercised through the
//! pipeline — with its own bevy-parity wrappers — by `tier3_sim_tide_verif`
//! and the dyncomp SH+RNP / polar-motion RUNs. A pipeline Tier-3 test of the
//! composite `T_inertial_pfix` would additionally need JEOD's EOP polar / UT1
//! table sourced independently (computational independence); that's deferred.
//!
//! Cross-validates our J2000 RNP model (IAU-76/FK5 precession, IAU-1980
//! 106-term nutation, GAST rotation, polar motion) against JEOD's
//! `SIM_RNP_J2000_prop` at all five RUNs.
//!
//! Two RUNs pin TAI−UTC and UT1−TAI via explicit overrides, so their time
//! setup is exact and deterministic (polar-motion-independent matrices):
//!
//! - `RUN_J2000_RNP_Transform` — the IAU-76/FK5 reduction reference epoch
//!   1991-04-06 07:51:28.386009 UTC, leap = 26 s, UT1−TAI = 0.402521 − 26 s.
//! - `RUN_J2000_RNP_init` — 1999-03-04 00:00:00 UTC, leap = 32 s,
//!   UT1−TAI = 0.64932 − 32 s.
//!
//! Three RUNs use JEOD's **default** EOP tables (no explicit override):
//!
//! - `RUN_J2000_RNP_Polar_off` — 1999-03-04 00:00:00 UTC, `enable_polar=False`.
//! - `RUN_J2000_RNP_prop_off`  — 1999-03-04 00:00:00 UTC, `enable_polar=True`.
//! - `RUN_J2000_RNP_prop`      — 1999-03-03 → 1999-03-04 (24 h), `enable_polar=True`.
//!
//! The RNP transform is a pure function of time (precession/nutation in TT,
//! GAST in UT1, polar motion in UT1) — independent of the integrator and of
//! any vehicle state — so this validation needs no trajectory propagation.
//!
//! ## How the default-EOP RUNs preserve computational independence
//!
//! JEOD's `time_ut1` defaults to interpolating `tai_to_ut1.cc` and its
//! `PolarMotionJ2000` defaults to interpolating `polar_motion/xpyp_daily.cc`.
//! Both data files are generated by JEOD's `parser.py` from the **same** IERS
//! "EOP 14 C04 (IAU2000)" input series (`eopc04_14_IAU2000.62-now`; the polar
//! `data/polar_motion/eopc04_…` is literally a symlink to the time model's
//! copy). That IERS series is *input data* on the same footing as gravity
//! coefficients — not JEOD simulation output — so we may source it.
//!
//! - **UT1**: driven through production [`SimulationTime`] backed by the
//!   committed [`astrodyn::default_eop_table`] (IERS C04 UT1−TAI, extracted
//!   from `tai_to_ut1.cc`).
//! - **Polar xp/yp**: the few daily IERS C04 entries bracketing these epochs,
//!   transcribed from `xpyp_daily.cc` into [`POLAR_DAILY_1999_03`] with full
//!   provenance, and interpolated by the exact port of JEOD's linear scheme
//!   (`polar_motion_j2000.cc::update_rotation`) in [`polar_xp_yp_rad`].
//!
//! JEOD's logged matrices are the *comparison target*, never an input — so
//! the composite `T_parent_this` (cols 33-41) plus the prec/nut/rot/NP
//! component matrices and the GAST/equation-of-equinoxes scalars are all
//! validated element-wise here, for every RUN, in JEOD's own configuration.

use astrodyn::{
    calendar_to_tjt, default_eop_table, default_leap_second_table, nutation_j2000,
    precession_j2000, rotation_j2000, CalendarDate, SimulationTime, TimeScaleId,
};
use astrodyn_verif_jeod::tier3_csv::test_data_path;
use glam::DMat3;

/// TT Julian centuries since J2000.0 from a TT truncated Julian time.
/// (TJT → JD: +2440000.5; centuries: (JD − 2451545)/36525.)
fn tt_centuries_from_tjt(tt_tjt: f64) -> f64 {
    (tt_tjt - 11544.5) / 36525.0
}

/// One logged record: time + the matrices we cross-validate. Stored as the
/// flat JEOD row-major `[ii][jj]` layout the snippet logs.
struct RnpRecord {
    sim_time: f64,
    theta_gast: f64,
    equa_of_equi: f64,
    nut: [f64; 9],
    prec: [f64; 9],
    rot: [f64; 9],
    /// JEOD's composite inertial→planet-fixed `T_parent_this`. For the
    /// default-EOP RUNs this folds in polar motion when `enable_polar=True`.
    tpt: [f64; 9],
    np: [f64; 9],
}

/// Column offsets in `rnp_*_rnp.csv` (see `RNP_VERIF_SNIPPET` in
/// `trick/generate_references.sh`): time, theta_gast, equa_of_equi,
/// output_vector[3], then nut/prec/rot/T_parent_this/NP as 3×3 row-major.
const NUT_OFF: usize = 6;
const PREC_OFF: usize = 15;
const ROT_OFF: usize = 24;
const TPT_OFF: usize = 33;
const NP_OFF: usize = 42;

fn load_rnp_csv(name: &str) -> Vec<RnpRecord> {
    let path = test_data_path(name);
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read SIM_RNP_J2000_prop CSV {}: {e}\n\
             Generate with Docker (see CLAUDE.md).",
            path.display()
        )
    });
    let mut out = Vec::new();
    for (i, line) in content.lines().enumerate() {
        if i == 0 || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(',').collect();
        assert!(
            f.len() >= 51,
            "RNP CSV line {}: expected >=51 columns, got {} (snippet drift?)",
            i + 1,
            f.len()
        );
        let p = |idx: usize| -> f64 { f[idx].trim().parse().unwrap() };
        let mat = |off: usize| -> [f64; 9] { std::array::from_fn(|k| p(off + k)) };
        out.push(RnpRecord {
            sim_time: p(0),
            theta_gast: p(1),
            equa_of_equi: p(2),
            nut: mat(NUT_OFF),
            prec: mat(PREC_OFF),
            rot: mat(ROT_OFF),
            tpt: mat(TPT_OFF),
            np: mat(NP_OFF),
        });
    }
    assert!(!out.is_empty(), "no data rows in {name}");
    out
}

/// JEOD logs `m[ii][jj]` row-major; our `DMat3` is column-major. Return our
/// matrix's element at (row `ii`, col `jj`) for comparison against the flat
/// row-major JEOD array index `ii*3 + jj`.
fn dmat_rowmajor(m: &DMat3) -> [f64; 9] {
    let c = m.to_cols_array(); // [m00,m10,m20, m01,m11,m21, m02,m12,m22] (col-major)
                               // row-major [ii*3+jj] = element(row ii, col jj) = c[jj*3 + ii]
    std::array::from_fn(|k| {
        let ii = k / 3;
        let jj = k % 3;
        c[jj * 3 + ii]
    })
}

fn max_abs_diff(a: &[f64; 9], b: &[f64; 9]) -> f64 {
    (0..9).fold(0.0_f64, |acc, k| acc.max((a[k] - b[k]).abs()))
}

/// Drive one RUN: build the exact-override time, walk the logged rows, and
/// compare our precession / nutation / GAST / NP matrices element-wise.
fn run_rnp_case(
    label: &str,
    csv_name: &str,
    epoch: CalendarDate,
    tai_minus_utc_s: f64,
    ut1_minus_tai_s: f64,
    mat_tol: f64,
    scalar_tol: f64,
) {
    let records = load_rnp_csv(csv_name);

    let utc_tjt = calendar_to_tjt(&epoch);
    let tai_tjt = utc_tjt + tai_minus_utc_s / 86_400.0;
    let mut time = SimulationTime::new(tai_tjt, default_leap_second_table());
    time.set_ut1_tai_offset(ut1_minus_tai_s);

    let (mut max_prec, mut max_nut, mut max_rot, mut max_np) = (0.0, 0.0, 0.0, 0.0);
    let (mut max_eoe, mut max_gast) = (0.0_f64, 0.0_f64);

    let mut prev_t = 0.0_f64;
    for (r, rec) in records.iter().enumerate() {
        if r > 0 {
            time.advance(rec.sim_time - prev_t);
        }
        prev_t = rec.sim_time;

        let tt_c = tt_centuries_from_tjt(time.tt_tjt());
        let gmst_s = time.get_seconds(TimeScaleId::GMST);

        let prec = precession_j2000::precession_matrix(tt_c);
        let nut = nutation_j2000::nutation(tt_c);
        let rot = rotation_j2000::gast_rotation_matrix(gmst_s, nut.equa_of_equi);
        // NP = nutation^T × precession^T (the composition our RNP uses).
        let np = nut.rotation.transpose() * prec.transpose();

        // JEOD's `earth.logging.{prec,nut,rot}_trans` store the component
        // transforms transposed relative to our matrices (the raw diffs are
        // exactly 2× the off-diagonal terms). The internal `NP_matrix` is
        // logged in our orientation. Compare each in its matching convention.
        max_prec = f64::max(
            max_prec,
            max_abs_diff(&dmat_rowmajor(&prec.transpose()), &rec.prec),
        );
        max_nut = f64::max(
            max_nut,
            max_abs_diff(&dmat_rowmajor(&nut.rotation.transpose()), &rec.nut),
        );
        max_rot = f64::max(
            max_rot,
            max_abs_diff(&dmat_rowmajor(&rot.transpose()), &rec.rot),
        );
        max_np = f64::max(max_np, max_abs_diff(&dmat_rowmajor(&np), &rec.np));
        max_eoe = max_eoe.max((nut.equa_of_equi - rec.equa_of_equi).abs());

        // GAST angle: our theta = (gmst + eoe)/240° normalized to [0, 2π).
        // `rem_euclid` already returns a non-negative result, so no further
        // branch is needed.
        let our_theta = ((gmst_s + nut.equa_of_equi) / 240.0)
            .to_radians()
            .rem_euclid(std::f64::consts::TAU);
        // Signed angular delta wrapped to (−π, π] so a tiny difference straddling
        // the 0/2π branch cut doesn't report a spurious ~2π error (matches
        // `tier3_rnp_component_comparison` in astrodyn_frames).
        let dtheta = (our_theta - rec.theta_gast + std::f64::consts::PI)
            .rem_euclid(std::f64::consts::TAU)
            - std::f64::consts::PI;
        max_gast = max_gast.max(dtheta.abs());
    }

    println!(
        "  {label}: {} rows — prec={max_prec:.2e} nut={max_nut:.2e} rot={max_rot:.2e} \
         NP={max_np:.2e} eoe={max_eoe:.2e} gast={max_gast:.2e}",
        records.len()
    );

    assert!(
        max_prec < mat_tol,
        "{label}: precession Δ {max_prec:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_nut < mat_tol,
        "{label}: nutation Δ {max_nut:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_rot < mat_tol,
        "{label}: GAST rotation Δ {max_rot:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_np < mat_tol,
        "{label}: NP Δ {max_np:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_eoe < scalar_tol,
        "{label}: equa_of_equi Δ {max_eoe:.3e} ≥ {scalar_tol:.1e}"
    );
    assert!(
        max_gast < scalar_tol,
        "{label}: GAST angle Δ {max_gast:.3e} ≥ {scalar_tol:.1e}"
    );
}

// non-recipe: RNP transform is a pure function of time; the scenario is the
// JEOD reference epoch + the exact leap/UT1 overrides from the RUN input deck,
// not a propagated trajectory. Tolerances are 1.05× observed max.
#[test]
fn rnp_j2000_transform_crossval() {
    run_rnp_case(
        "rnp_transform",
        "rnp_transform_rnp.csv",
        CalendarDate::new(1991, 4, 6, 7, 51, 28.386_009),
        26.0,
        0.402_521 - 26.0,
        // Observed: prec/nut/NP ~1e-18, rot 8.5e-12 (GMST-conversion FP floor);
        // GAST angle 1.13e-11. Tolerances 1.05× observed max (CLAUDE.md).
        9.0e-12,
        1.2e-11,
    );
}

// non-recipe: same pure-function-of-time scenario as `rnp_j2000_transform_crossval`
// above, at a second JEOD reference epoch (1999-03-04) with its own exact
// leap/UT1 overrides. Tolerances are 1.05× observed max.
#[test]
fn rnp_j2000_init_crossval() {
    run_rnp_case(
        "rnp_init",
        "rnp_init_rnp.csv",
        CalendarDate::new(1999, 3, 4, 0, 0, 0.0),
        32.0,
        0.649_32 - 32.0,
        // Observed: matrices ≤ 4.74e-12, GAST angle 4.85e-12. 1.05× observed.
        5.0e-12,
        5.1e-12,
    );
}

// ─────────────────────────────────────────────────────────────────────────
// Default-EOP RUNs (Polar_off / prop_off / prop)
//
// These RUNs do NOT override the time/polar tables; JEOD interpolates its
// default IERS C04 data. We drive UT1 through the committed EopTable and the
// polar xp/yp through the daily IERS C04 entries transcribed below, then
// compare our composite `T_parent_this` element-wise to JEOD's logged matrix.
// ─────────────────────────────────────────────────────────────────────────

/// Arcseconds → radians (JEOD `polar_motion/xpyp.mako` `ARCSECONDS_TO_RADIANS`).
const ARCSEC_TO_RAD: f64 = 4.848_136_811_095_36e-6;

/// Daily IERS "EOP 14 C04 (IAU2000)" polar-motion entries `(mjd, xp_arcsec,
/// yp_arcsec)` bracketing the 1999-03 epochs, transcribed verbatim from JEOD's
/// `models/environment/RNP/RNPJ2000/data/polar_motion/src/xpyp_daily.cc`
/// (indices 13573–13577). This is IERS *input* data — the same series the UT1
/// table derives from — not JEOD simulation output, so transcribing the handful
/// of entries the test needs preserves computational independence (cf. the
/// inline arcsec constants in `run_verification/sim_polar_motion.rs`).
///
/// Independent variable is the UT1 Modified Julian Date. At UTC midnight the
/// UT1 MJD is ~0.9997 (UT1−TAI ≈ −31.35 s), so 1999-03-04 00:00 UTC brackets
/// MJD [51240, 51241] and 1999-03-03 00:00 UTC brackets MJD [51239, 51240] —
/// hence three days of data are required for the t=0/t=24 h `prop` RUN.
const POLAR_DAILY_1999_03: &[(f64, f64, f64)] = &[
    (51239.0, 0.068952, 0.241610), // 1999 3 2
    (51240.0, 0.068174, 0.241636), // 1999 3 3
    (51241.0, 0.067500, 0.241843), // 1999 3 4
    (51242.0, 0.066650, 0.242182), // 1999 3 5
];

/// Port of JEOD `polar_motion_j2000.cc::update_rotation`'s table lookup:
/// linear interpolation of xp/yp (in radians) on the UT1 MJD, clamping to the
/// boundary values outside the table. Returns `(xp_rad, yp_rad)`.
///
/// # Panics
/// Panics if `ut1_mjd` falls outside [`POLAR_DAILY_1999_03`] — the bundled
/// window only covers the SIM_RNP_J2000_prop epochs; a lookup elsewhere means
/// the test was pointed at an epoch the fixture does not cover.
fn polar_xp_yp_rad(ut1_mjd: f64) -> (f64, f64) {
    let tbl = POLAR_DAILY_1999_03;
    let last = tbl.len() - 1;
    assert!(
        ut1_mjd >= tbl[0].0 && ut1_mjd <= tbl[last].0,
        "UT1 MJD {ut1_mjd} outside the bundled polar fixture [{}, {}]; \
         extend POLAR_DAILY_1999_03 from xpyp_daily.cc for this epoch",
        tbl[0].0,
        tbl[last].0
    );
    // Bracket: largest i with mjd[i] <= ut1_mjd < mjd[i+1] (JEOD's loop).
    let mut idx = 0usize;
    for i in 0..last {
        if ut1_mjd < tbl[i + 1].0 {
            idx = i;
            break;
        }
    }
    let (m0, x0, y0) = tbl[idx];
    let (m1, x1, y1) = tbl[idx + 1];
    let frac = (ut1_mjd - m0) / (m1 - m0);
    let xp = (x0 + (x1 - x0) * frac) * ARCSEC_TO_RAD;
    let yp = (y0 + (y1 - y0) * frac) * ARCSEC_TO_RAD;
    (xp, yp)
}

/// Drive one default-EOP RUN: build the epoch time backed by the committed
/// IERS C04 UT1 [`EopTable`](astrodyn::EopTable), walk the logged rows, and
/// compare our prec/nut/GAST/NP components **and** the composite
/// `T_parent_this` element-wise to JEOD. When `enable_polar` is true the
/// composite folds in the polar matrix from [`polar_xp_yp_rad`].
///
/// Unlike `run_rnp_case`, UT1−TAI is *not* an explicit override here: it is
/// interpolated per-step from the EOP table inside `SimulationTime::advance`,
/// exactly as JEOD's `time_ut1` default converter does.
#[allow(clippy::too_many_arguments)]
fn run_rnp_default_eop_case(
    label: &str,
    csv_name: &str,
    epoch: CalendarDate,
    tai_minus_utc_s: f64,
    enable_polar: bool,
    mat_tol: f64,
    tpt_tol: f64,
    scalar_tol: f64,
) {
    let records = load_rnp_csv(csv_name);

    let utc_tjt = calendar_to_tjt(&epoch);
    let tai_tjt = utc_tjt + tai_minus_utc_s / 86_400.0;
    // Production UT1: interpolate the committed IERS C04 UT1−TAI table every
    // step (JEOD `time_ut1` default mode), not a fixed override.
    let mut time = SimulationTime::new(tai_tjt, default_leap_second_table())
        .with_eop_table(default_eop_table());

    let (mut max_prec, mut max_nut, mut max_rot, mut max_np) = (0.0, 0.0, 0.0, 0.0);
    let (mut max_tpt, mut max_eoe, mut max_gast) = (0.0_f64, 0.0_f64, 0.0_f64);

    let mut prev_t = 0.0_f64;
    for (r, rec) in records.iter().enumerate() {
        if r > 0 {
            time.advance(rec.sim_time - prev_t);
        }
        prev_t = rec.sim_time;

        let tt_c = tt_centuries_from_tjt(time.tt_tjt());
        let gmst_s = time.get_seconds(TimeScaleId::GMST);

        let prec = precession_j2000::precession_matrix(tt_c);
        let nut = nutation_j2000::nutation(tt_c);
        let rot = rotation_j2000::gast_rotation_matrix(gmst_s, nut.equa_of_equi);
        let np = nut.rotation.transpose() * prec.transpose();

        // Polar lookup keyed on the UT1 Modified Julian Date, matching JEOD
        // `rnp_j2000.cc:179` (`time_ut1.trunc_julian_time + 40000`).
        let polar = if enable_polar {
            let ut1_mjd = time.ut1_julian_date() - 2_400_000.5;
            Some(polar_xp_yp_rad(ut1_mjd))
        } else {
            None
        };

        // Composite inertial→pfix exactly as JEOD assembles it:
        // T_parent_this = polar^T × rotation^T × (nutation^T × precession^T).
        let tpt =
            rotation_j2000::compute_t_parent_this_from_tjt_with_polar(gmst_s, time.tt_tjt(), polar);

        // Component matrices share the orientation conventions documented in
        // `run_rnp_case`. T_parent_this is logged in our (column-mapped) layout.
        max_prec = f64::max(
            max_prec,
            max_abs_diff(&dmat_rowmajor(&prec.transpose()), &rec.prec),
        );
        max_nut = f64::max(
            max_nut,
            max_abs_diff(&dmat_rowmajor(&nut.rotation.transpose()), &rec.nut),
        );
        max_rot = f64::max(
            max_rot,
            max_abs_diff(&dmat_rowmajor(&rot.transpose()), &rec.rot),
        );
        max_np = f64::max(max_np, max_abs_diff(&dmat_rowmajor(&np), &rec.np));
        max_tpt = f64::max(max_tpt, max_abs_diff(&dmat_rowmajor(&tpt), &rec.tpt));
        max_eoe = max_eoe.max((nut.equa_of_equi - rec.equa_of_equi).abs());

        let our_theta = ((gmst_s + nut.equa_of_equi) / 240.0)
            .to_radians()
            .rem_euclid(std::f64::consts::TAU);
        let dtheta = (our_theta - rec.theta_gast + std::f64::consts::PI)
            .rem_euclid(std::f64::consts::TAU)
            - std::f64::consts::PI;
        max_gast = max_gast.max(dtheta.abs());
    }

    println!(
        "  {label}: {} rows polar={enable_polar} — prec={max_prec:.2e} nut={max_nut:.2e} \
         rot={max_rot:.2e} NP={max_np:.2e} T_parent_this={max_tpt:.2e} \
         eoe={max_eoe:.2e} gast={max_gast:.2e}",
        records.len()
    );

    assert!(
        max_prec < mat_tol,
        "{label}: precession Δ {max_prec:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_nut < mat_tol,
        "{label}: nutation Δ {max_nut:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_rot < mat_tol,
        "{label}: GAST rotation Δ {max_rot:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_np < mat_tol,
        "{label}: NP Δ {max_np:.3e} ≥ {mat_tol:.1e}"
    );
    assert!(
        max_tpt < tpt_tol,
        "{label}: composite T_parent_this Δ {max_tpt:.3e} ≥ {tpt_tol:.1e}"
    );
    assert!(
        max_eoe < scalar_tol,
        "{label}: equa_of_equi Δ {max_eoe:.3e} ≥ {scalar_tol:.1e}"
    );
    assert!(
        max_gast < scalar_tol,
        "{label}: GAST angle Δ {max_gast:.3e} ≥ {scalar_tol:.1e}"
    );
}

// non-recipe: default-EOP RNP scenario — UT1 from the committed IERS C04 table,
// polar motion DISABLED (`enable_polar=False`). Validates the composite
// `T_parent_this = rotation^T × NP` assembly under JEOD's real default UT1.
// 1999-03-04 00:00:00 UTC, leap = 32 s. Tolerances are 1.05× observed max.
#[test]
fn rnp_j2000_polar_off_crossval() {
    run_rnp_default_eop_case(
        "rnp_polar_off",
        "rnp_polar_off_rnp.csv",
        CalendarDate::new(1999, 3, 4, 0, 0, 0.0),
        32.0,
        false,
        // Observed: prec/nut/NP ~1e-20, rot 4.40e-12, T_parent_this 4.40e-12,
        // GAST angle 4.56e-12 (GMST-conversion FP floor). 1.05× observed max.
        4.7e-12,
        4.7e-12,
        4.8e-12,
    );
}

// non-recipe: default-EOP RNP scenario with polar motion ENABLED
// (`enable_polar=True`), single 1 s record. UT1 from the committed IERS C04
// table; polar xp/yp interpolated from the daily IERS C04 entries. Validates
// the full composite `T_parent_this = polar^T × rotation^T × NP`.
// 1999-03-04 00:00:00 UTC, leap = 32 s. Tolerances are 1.05× observed max.
#[test]
fn rnp_j2000_prop_off_crossval() {
    run_rnp_default_eop_case(
        "rnp_prop_off",
        "rnp_prop_off_rnp.csv",
        CalendarDate::new(1999, 3, 4, 0, 0, 0.0),
        32.0,
        true,
        // Observed: prec/nut/NP ~1e-20, rot 4.74e-12, T_parent_this 4.74e-12
        // (polar fold-in is FP-exact vs JEOD), GAST 5.02e-12. 1.05× observed.
        5.0e-12,
        5.0e-12,
        5.3e-12,
    );
}

// non-recipe: default-EOP RNP scenario with polar motion ENABLED, propagated
// over 24 h (t=0 at 1999-03-03 and t=86400 s at 1999-03-04, the two logged
// rows). Exercises UT1 + polar interpolation across two daily-table brackets.
// 1999-03-03 00:00:00 UTC, leap = 32 s. Tolerances are 1.05× observed max.
#[test]
fn rnp_j2000_prop_crossval() {
    run_rnp_default_eop_case(
        "rnp_prop",
        "rnp_prop_rnp.csv",
        CalendarDate::new(1999, 3, 3, 0, 0, 0.0),
        32.0,
        true,
        // Observed: prec/nut/NP ~1e-20, rot 6.94e-8, T_parent_this 6.94e-8,
        // GAST 7.32e-8. The 24 h GMST/UT1 accumulation at t=86400 dominates
        // (T_parent_this tracks the rot error, so the polar interpolation
        // across the daily-table bracket is itself consistent). 1.05× observed.
        7.3e-8,
        7.3e-8,
        7.7e-8,
    );
}
