[package]
name = "jeod_atmosphere"
description = "Atmospheric density models (exponential, MET) for bevy_jeod"
readme = "README.md"
keywords = ["atmosphere", "drag", "orbital-mechanics", "aerospace"]
categories = ["science", "aerospace"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
jeod_quantities = { path = "../jeod_quantities", version = "0.1.0" }
glam = { workspace = true }
uom = { workspace = true }

[dev-dependencies]
jeod_test_data = { path = "../jeod_test_data", version = "0.1.0" }
